---
fixtures:
  repositories:
    ruby_task_helper: https://github.com/puppetlabs/puppetlabs-ruby_task_helper.git
    simplib: https://github.com/simp/pupmod-simp-simplib.git
    stdlib: https://github.com/simp/puppetlabs-stdlib.git
